project_id = "mb-safe-arrival-ux"

[api]
enabled = true
port = 59321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]

[db]
port = 59322
major_version = 15

[studio]
enabled = true
port = 59323

[inbucket]
enabled = true
port = 59324

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback", "http://localhost:3000/onboarding"]

[auth.email]
enable_confirmations = true

[storage]
enabled = true

[analytics]
enabled = false
