import { headers } from "next/headers";
import type { Metadata, Viewport } from "next";
import { GoogleAnalytics } from "@next/third-parties/google";
import CapacitorBackButton from "@/components/CapacitorBackButton";
import { ServiceWorkerRegistration } from "@/components/pwa/service-worker-registration";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { resolveBuildId } from "@/lib/pwa/update";
import { getSiteUrl } from "@/lib/seo";
import "./globals.css";

/**
 * iOS "Add to Home Screen" splash images (portrait only, this app is
 * portrait-locked). Matched by exact device logical size + pixel ratio, which
 * is the only way Safari selects the right apple-touch-startup-image; there is
 * no single responsive entry. Files generated by
 * scripts/generate-splash-assets.mjs at each size's native pixel dimensions
 * (logical size x scale).
 *
 * Shape matches Next's internal AppleImageDescriptor ({ url, media }), typed
 * out by hand rather than imported from next/dist since that path is an
 * internal, unversioned module.
 */
const APPLE_STARTUP_IMAGES: { url: string; media: string }[] = [
  {
    url: "/splash/iphone-se.jpg",
    media: "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    url: "/splash/iphone-8.jpg",
    media: "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    url: "/splash/iphone-8-plus.jpg",
    media: "(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    url: "/splash/iphone-x.jpg",
    media: "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    url: "/splash/iphone-14-pro.jpg",
    media: "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    url: "/splash/iphone-14-pro-max.jpg",
    media: "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    url: "/splash/ipad.jpg",
    media: "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    url: "/splash/ipad-pro-11.jpg",
    media: "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    url: "/splash/ipad-pro-12.9.jpg",
    media: "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  }
];

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fbfaff" },
    { media: "(prefers-color-scheme: dark)", color: "#0b0f19" }
  ]
};

export const metadata: Metadata = {
  metadataBase: getSiteUrl(),
  title: {
    default: "Mad Buddy",
    template: "%s | Mad Buddy"
  },
  description: "When your Muddies are close, they glow, private proximity for mutually approved friends.",
  applicationName: "Mad Buddy",
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Mad Buddy",
    // iOS Safari's "Add to Home Screen" splash has no relation to the Web App
    // Manifest's `icons` array; it only reads these apple-touch-startup-image
    // link tags, matched by exact device media query. Generated from
    // public/brand/launch-hero.png via scripts/generate-splash-assets.mjs,
    // same source photo as the native (Capacitor) splash screen.
    startupImage: APPLE_STARTUP_IMAGES,
  },
  formatDetection: { telephone: false },
  openGraph: {
    title: "Mad Buddy",
    description: "When your Muddies are close, they glow.",
    type: "website",
    images: [{ url: "/brand/mad-buddy-logo-414.png", width: 414, height: 414, alt: "Mad Buddy" }]
  },
  twitter: {
    card: "summary_large_image",
    title: "Mad Buddy",
    description: "When your Muddies are close, they glow.",
    images: ["/brand/mad-buddy-logo-414.png"]
  },
  robots: {
    index: true,
    follow: true
  }
};

type RootLayoutProps = {
  children: React.ReactNode;
};

const themeScript = `
(function() {
  try {
    var storedPreference = window.localStorage.getItem('mad-buddy-theme-preference');
    var preference = (storedPreference === 'light' || storedPreference === 'dark') ? storedPreference : 'system';
    var prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    var mode = preference === 'system' ? (prefersDark ? 'dark' : 'light') : preference;
    document.documentElement.classList.toggle('dark', mode === 'dark');
    document.documentElement.style.colorScheme = mode;

    var storedAccent = window.localStorage.getItem('mad-buddy-accent-color');
    var validAccents = ['orange', 'blue', 'violet', 'green', 'red', 'teal'];
    document.documentElement.setAttribute('data-accent', validAccents.indexOf(storedAccent) !== -1 ? storedAccent : 'orange');
  } catch (error) {
  }
})();
`;

export default async function RootLayout({ children }: RootLayoutProps) {
  const buildId = resolveBuildId(process.env);
  const gaMeasurementId =
    process.env.NODE_ENV === "production" ? process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID : undefined;
  // The CSP nonce proxy.ts minted for this request. The theme bootstrap is an
  // inline script, so under the enforced nonce-based CSP it must carry it.
  const nonce = (await headers()).get("x-nonce") ?? undefined;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script id="theme-script" nonce={nonce} dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body suppressHydrationWarning>
        <ThemeProvider>
          <CapacitorBackButton />
          {children}
          <ServiceWorkerRegistration currentBuildId={buildId} />
        </ThemeProvider>
        {gaMeasurementId ? <GoogleAnalytics gaId={gaMeasurementId} nonce={nonce} /> : null}
      </body>
    </html>
  );
}
