import { headers } from "next/headers";
import type { Metadata, Viewport } from "next";
import { GoogleAnalytics } from "@next/third-parties/google";
import CapacitorBackButton from "@/components/CapacitorBackButton";
import { ServiceWorkerRegistration } from "@/components/pwa/service-worker-registration";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { resolveBuildId } from "@/lib/pwa/update";
import { getSiteUrl } from "@/lib/seo";
import "./globals.css";
import "./icon-polish.css";

/**
 * iOS "Add to Home Screen" splash images (portrait only, this app is
 * portrait-locked). Matched by exact device logical size + pixel ratio, which
 * is the only way Safari selects the right apple-touch-startup-image; there is
 * no single responsive entry. Files generated by
 * scripts/generate-splash-assets.mjs at each size's native pixel dimensions
 * (logical size x scale).
 *
 * Shape matches Next's internal AppleImageDescriptor ({ url, media }), typed
 * out by hand rather than imported from next/dist since that path is an
 * internal, unversioned module.
 */
const APPLE_STARTUP_IMAGES: { url: string; media: string }[] = [
  {
    url: "/splash/iphone-se.jpg",
    media: "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    url: "/splash/iphone-8.jpg",
    media: "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    url: "/splash/iphone-8-plus.jpg",
    media: "(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    url: "/splash/iphone-x.jpg",
    media: "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    url: "/splash/iphone-14-pro.jpg",
    media: "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    url: "/splash/iphone-14-pro-max.jpg",
    media: "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
  },
  {
    url: "/splash/ipad.jpg",
    media: "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    url: "/splash/ipad-pro-11.jpg",
    media: "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  },
  {
    url: "/splash/ipad-pro-12.9.jpg",
    media: "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
  }
];

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fbfaff" },
    { media: "(prefers-color-scheme: dark)", color: "#0b0f19" }
  ]
};

export const metadata: Metadata = {
  metadataBase: getSiteUrl(),
  title: {
    default: "Mad Buddy",
    template: "%s | Mad Buddy"
  },
  description: "When your Muddies are close, they glow, private proximity for mutually approved friends.",
  applicationName: "Mad Buddy",
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Mad Buddy",
    // iOS Safari's "Add to Home Screen" splash has no relation to the Web App
    // Manifest's `icons` array; it only reads these apple-touch-startup-image
    // link tags, matched by exact device media query. Generated from
    // public/brand/launch-hero.png via scripts/generate-splash-assets.mjs,
    // from the approved native/PWA splash artwork.
    startupImage: APPLE_STARTUP_IMAGES,
  },
  formatDetection: { telephone: false },
  openGraph: {
    title: "Mad Buddy",
    description: "When your Muddies are close, they glow.",
    type: "website",
    images: [{ url: "/brand/mad-buddy-social-share.jpg", width: 1200, height: 630, alt: "Mad Buddy" }]
  },
  twitter: {
    card: "summary_large_image",
    title: "Mad Buddy",
    description: "When your Muddies are close, they glow.",
    images: ["/brand/mad-buddy-social-share.jpg"]
  },
  robots: {
    index: true,
    follow: true
  }
};

type RootLayoutProps = {
  children: React.ReactNode;
};

const themeScript = `
(function() {
  // OUTSIDE the try, and first.
  //
  // This marks "JavaScript is running", which is what gates the landing
  // reveal animation. Progressive enhancement in the strict sense: without
  // it the hero renders plainly and is readable; with it the animation runs.
  //
  // It must not sit inside the try below -- localStorage throws in some
  // privacy modes, and if that exception skipped this line the landing page
  // would stay blank for exactly the privacy-conscious users this product is
  // built for.
  document.documentElement.classList.add('js');

  try {
    var storedPreference = window.localStorage.getItem('mad-buddy-theme-preference');
    var preference = (storedPreference === 'light' || storedPreference === 'dark') ? storedPreference : 'system';
    var prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    var mode = preference === 'system' ? (prefersDark ? 'dark' : 'light') : preference;
    document.documentElement.classList.toggle('dark', mode === 'dark');
    document.documentElement.style.colorScheme = mode;

    var storedAccent = window.localStorage.getItem('mad-buddy-accent-color');
    var validAccents = ['orange', 'blue', 'violet', 'green', 'red', 'teal'];
    document.documentElement.setAttribute('data-accent', validAccents.indexOf(storedAccent) !== -1 ? storedAccent : 'orange');
  } catch (error) {
  }
})();
`;

export default async function RootLayout({ children }: RootLayoutProps) {
  const buildId = resolveBuildId(process.env);
  const gaMeasurementId =
    process.env.NODE_ENV === "production" ? process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID : undefined;
  // The CSP nonce proxy.ts minted for this request. The theme bootstrap is an
  // inline script, so under the enforced nonce-based CSP it must carry it.
  const nonce = (await headers()).get("x-nonce") ?? undefined;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* suppressHydrationWarning is required here, and ONLY here, because of
            CSP nonce-hiding — a browser behaviour, not an app bug.
            The CSP spec requires a user agent to EMPTY the `nonce` content
            attribute once the document has loaded, so a stylesheet cannot use
            an attribute selector to exfiltrate the value. Chromium does exactly
            that: after load `getAttribute("nonce")` is `""` while the real value
            survives on the `.nonce` IDL property.
            React hydrates AFTER that blanking has happened, compares its own
            `nonce` prop against the emptied DOM attribute, and reports
            `nonce="n2v8..."` (client) vs `nonce=""` (server). Because this
            script lives in the ROOT layout, the warning appeared on every route
            in the app — which is why it presented as an "app-wide hydration
            warning confirmed on /settings" rather than as a bug in any one page.
            Nothing is actually mismatched: proxy.ts mints the nonce, the
            response header and the served HTML carry the SAME value (verified),
            and the script executes under the enforced CSP. Suppressing the
            comparison on this one element is the correct fix; removing the nonce
            would break the CSP, and there is no way to stop the browser hiding
            the attribute. Scoped to this element only, so genuine mismatches
            anywhere else still surface. */}
        <script
          id="theme-script"
          nonce={nonce}
          suppressHydrationWarning
          dangerouslySetInnerHTML={{ __html: themeScript }}
        />
      </head>
      <body suppressHydrationWarning>
        <ThemeProvider>
          <CapacitorBackButton />
          {children}
          <ServiceWorkerRegistration currentBuildId={buildId} />
        </ThemeProvider>
        {gaMeasurementId ? <GoogleAnalytics gaId={gaMeasurementId} nonce={nonce} /> : null}
      </body>
    </html>
  );
}
