import { useEffect, useState } from "react";
import { ShieldCheck } from "lucide-react";
import { api } from "../lib/api";

type Score = { total: number; level: { label: string }; nextLevel: { label: string } | null; pointsToNext: number; progressPercent: number; categories: Array<{ label: string; points: number }>; recentActivity: Array<{ id: string; label: string; points: number }>; earnedReward: { plan: "buddy_plus" | "buddy_pro"; status: "active" | "grace"; expiresAt: string; graceEndsAt: string | null } | null };

export function BuddyScoreScreen() {
  const [score, setScore] = useState<Score | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { void api.get<Score>("/api/buddy-score").then((result) => result.ok ? setScore(result.data) : setError(result.error)); }, []);
  return <div className="mx-auto w-full max-w-lg space-y-5 px-4 pt-6"><header><h1 className="text-2xl font-semibold">Buddy Score</h1><p className="mt-1 text-sm text-muted-foreground">Your private trust summary.</p></header>{error ? <p className="rounded-xl bg-destructive/10 p-4 text-sm text-destructive">{error}</p> : !score ? <p className="text-sm text-muted-foreground">Loading your score...</p> : <><section className="rounded-3xl border border-border bg-card/50 p-6"><ShieldCheck className="h-6 w-6 text-orange-400" aria-hidden="true" /><p className="mt-4 text-5xl font-semibold">{score.total}</p><p className="mt-1 font-semibold text-orange-300">{score.level.label}</p>{score.nextLevel ? <><div className="mt-5 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-orange-500" style={{ width: `${score.progressPercent}%` }} /></div><p className="mt-2 text-xs text-muted-foreground">{score.pointsToNext} points to {score.nextLevel.label}</p></> : null}</section>{score.earnedReward ? <section className="rounded-2xl border border-orange-500/30 bg-orange-500/[0.06] p-4"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-orange-400">Earned premium</p><h2 className="mt-2 font-semibold">{score.earnedReward.plan === "buddy_pro" ? "Buddy Pro" : "Buddy Plus"} access</h2><p className="mt-1 text-sm text-muted-foreground">{score.earnedReward.status === "grace" ? "Grace period active" : "Unlocked through trusted participation"}</p><p className="mt-2 text-xs text-muted-foreground">Ends {new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(score.earnedReward.graceEndsAt ?? score.earnedReward.expiresAt))}</p></section> : null}<section className="rounded-2xl border border-border bg-card/40 p-4"><h2 className="font-semibold">Earning categories</h2><div className="mt-3 divide-y divide-border/70">{score.categories.length ? score.categories.map((item) => <div key={item.label} className="flex justify-between py-3 text-sm"><span className="text-muted-foreground">{item.label}</span><strong>{item.points > 0 ? "+" : ""}{item.points}</strong></div>) : <p className="py-4 text-sm text-muted-foreground">Complete genuine activity to begin earning points.</p>}</div></section></>}</div>;
}
