import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowRight, Award, Check, CheckCircle2, Circle, LockKeyhole, ShieldCheck, UserRound } from "lucide-react";
import type { MyProgressData } from "@/lib/progress/my-progress";
import { api } from "../lib/api";

export function BuddyScoreScreen() {
  const navigate = useNavigate();
  const [progress, setProgress] = useState<MyProgressData | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { void api.get<MyProgressData>("/api/buddy-score").then((result) => result.ok ? setProgress(result.data) : setError(result.error)); }, []);
  if (error) return <div className="mx-auto w-full max-w-lg px-4 pt-6"><p className="rounded-xl bg-destructive/10 p-4 text-sm text-destructive">{error}</p></div>;
  if (!progress) return <div className="mx-auto w-full max-w-lg px-4 pt-6"><p className="text-sm text-muted-foreground">Loading your progress...</p></div>;
  const { score, profileCompletion, achievements, milestones, timeline, journey } = progress;
  return <div className="mx-auto w-full max-w-lg space-y-7 px-4 pb-8 pt-6">
    <header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Private to you</p><h1 className="mt-2 text-2xl font-semibold">My Progress</h1><p className="mt-1 text-sm leading-6 text-muted-foreground">Your trust, identity, and meaningful participation over time.</p></header>

    <section><Heading title="Identity" /><div className="mt-3 grid grid-cols-2 gap-3"><Identity label="Reputation" value={score.level.label} icon={ShieldCheck} /><Identity label="Buddy Score" value={String(score.total)} icon={Award} /><Identity label="Profile" value={`${profileCompletion.percent}% complete`} icon={UserRound} /></div></section>

    <section><Heading title="Buddy Score" /><div className="mt-3 rounded-2xl border border-border bg-card/40 p-5"><ShieldCheck className="h-6 w-6 text-primary" aria-hidden="true" /><p className="mt-4 text-5xl font-semibold">{score.total}</p><p className="mt-1 font-semibold text-primary">{score.level.label}</p>{score.nextLevel ? <><div className="mt-5 h-2 overflow-hidden rounded-full bg-secondary" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={score.progressPercent}><div className="h-full rounded-full bg-primary motion-reduce:transition-none" style={{ width: `${score.progressPercent}%` }} /></div><p className="mt-2 text-xs text-muted-foreground">{score.pointsToNext} points to {score.nextLevel.label}</p></> : null}<p className="mt-5 border-t border-border pt-4 text-xs text-muted-foreground">Your exact score and progress are visible only to you.</p></div></section>

    <section><Heading title="Achievements" detail={`${achievements.unlockedCount} unlocked`} />{achievements.featured.length ? <><div className="mt-3 space-y-2">{achievements.featured.map((achievement) => <div key={achievement.code} className="rounded-xl border border-border bg-card/40 p-4"><p className="font-semibold">{achievement.name}</p><p className="mt-1 text-sm text-muted-foreground">{achievement.description}</p></div>)}</div><div className="mt-3 flex flex-wrap gap-2"><span className="w-full text-xs font-semibold text-muted-foreground">Recently earned</span>{achievements.recent.map((achievement) => <span key={achievement.code} className="rounded-full border border-border px-3 py-1.5 text-xs font-medium">{achievement.name}</span>)}</div></> : <Empty text="Achievements appear after meaningful milestones. There is no rush." />}</section>

    <section><Heading title="Journey Progress" detail={`${journey.completedCount}/${journey.totalCount}`} /><div className="mt-3 divide-y divide-border overflow-hidden rounded-2xl border border-border bg-card/40">{journey.steps.map((step) => <div key={step.id} className="flex gap-3 px-4 py-3.5"><span className="mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-full border border-border">{step.state === "completed" ? <Check className="h-3.5 w-3.5 text-emerald-500" aria-hidden="true" /> : step.state === "current" ? <Circle className="h-3 w-3 fill-primary text-primary" aria-hidden="true" /> : <LockKeyhole className="h-3 w-3 text-muted-foreground" aria-hidden="true" />}</span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{step.title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{step.state === "locked" ? "Complete the previous step to continue." : step.description}</p>{step.state === "current" ? <button type="button" className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-primary" onClick={() => navigate(step.destination)}>Continue <ArrowRight className="h-3.5 w-3.5" aria-hidden="true" /></button> : null}</div></div>)}</div></section>

    <section><Heading title="Milestones" />{milestones.length ? <div className="mt-3 divide-y divide-border rounded-2xl border border-border bg-card/40">{milestones.map((milestone) => <div key={milestone.key} className="flex items-center gap-3 px-4 py-3"><CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-500" aria-hidden="true" /><span className="text-sm font-medium">{milestone.label}</span></div>)}</div> : <Empty text="Completed milestones will appear here." />}</section>

    <section><Heading title="Recent Activity" />{timeline.length ? <div className="mt-3 divide-y divide-border rounded-2xl border border-border bg-card/40">{timeline.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 px-4 py-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{item.label}</p><p className="text-xs text-muted-foreground">{item.detail}</p></div>{item.points !== null ? <span className={item.points >= 0 ? "text-sm font-semibold text-emerald-500" : "text-sm font-semibold text-red-500"}>{item.points > 0 ? "+" : ""}{item.points}</span> : null}</div>)}</div> : <Empty text="Your verified progress will appear here." />}</section>
  </div>;
}
function Heading({ title, detail }: { title: string; detail?: string }) { return <div className="flex items-end justify-between gap-3"><h2 className="text-lg font-semibold">{title}</h2>{detail ? <p className="text-xs text-muted-foreground">{detail}</p> : null}</div>; }
function Identity({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Award }) { return <div className="min-h-28 rounded-xl border border-border bg-card/40 p-4"><Icon className="h-4 w-4 text-primary" aria-hidden="true" /><p className="mt-4 text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>; }
function Empty({ text }: { text: string }) { return <p className="mt-3 rounded-xl border border-border bg-card/40 p-4 text-sm text-muted-foreground">{text}</p>; }
